services:
  ollamamodelmanager:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ollamamodelmanager:latest
    container_name: ollamamodelmanager
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_ENDPOINTS=${OLLAMA_ENDPOINTS:-ollama:11434}